### ISSUE TITLE
进行全球解析时遇到未知错误: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by AdorableJiang** [miyouzi/akamTester#11]
Unbuntu和Windows下均存在同样问题，请问该如何解决

进行全球解析时遇到未知错误: 'NoneType' object has no attribute 'get'
将读取本地保存的ip列表

**Comment by chenyang12315** [comment]
您好！
我遇到同样的问题。本机系统Win10 2004 x64，海外网络。

> 当前akamTester版本: 4.0
第一次解析:
正在对 upos-hz-mirrorakam.akamaized.net 进行全球解析……
进行全球解析时遇到未知错误: 'NoneType' object has no attribute 'get'
将读取本地保存的ip列表

> 共取得 8 个 IP, 开始测试延迟

**Comment by miyouzi** [comment]
[v4.1](https://github.com/miyouzi/akamTester/releases/tag/v4.1) 修复
