### ISSUE TITLE
作者大大好，我直接用的程序测试ping但是测试出几十个ip之后就闪退了，请问是什么原因

### ISSUE THREAD

**Issue by xinwu322** [miyouzi/akamTester#3]

**Comment by miyouzi** [comment]
你是Win7么？有反馈Win7需要管理员权限运行。

**Comment by xinwu322** [comment]
我是win10，用不用管理员权限都是这种状况。。。

**Comment by miyouzi** [comment]
打开一个cmd窗口，将程序拖入后运行，截图上来，看看报了什么错

**Comment by xinwu322** [comment]
![ip](https://user-images.githubusercontent.com/61226567/75116067-6acf9800-569f-11ea-89df-68c1f6f7a2f5.png)
在cmd里运行没有报错但是最后结果出现这种类似乱码的东西

**Comment by xinwu322** [comment]
[1m[32m基于当前网络环境, 以下为延迟低于100ms的IP[0m
[1m[32m23.32.248.8  平均延迟:   57.55 ms[0m
[1m[32m23.32.248.42  平均延迟:   76.36 ms[0m

emmm我没开ss不知道图片有没有上传好，结果就是上面这三行

**Comment by miyouzi** [comment]
你尝试一下这个新版本。
[akamTester_v3.2.zip](https://github.com/miyouzi/akamTester/files/4243002/akamTester_v3.2.zip)

**Comment by xinwu322** [comment]
哇现在好了，非常感谢
